### ISSUE TITLE
Crayon the information

### ISSUE THREAD

**Issue by Athanasiamo** [elbersb/tidylog#17]
I cant express how much this package is making my workflow better! Brilliant.

I was wondering if you might consider crayoning the logs so they are more easily distinguishable from errors and warnings? This would at least help me alot when running larger scripts where I have known warnings I ignore, but want to catch errors.

**Comment by elbersb** [comment]
Thanks, glad you like it!

Tidylog uses `message` (a built-in R function), which doesn't allow for any customization. This is the canonical way to do it, because then you can use things like `suppressMessages` and tidylog will behave properly. However, you can supply your own printing function to tidylog (see Readme for more information). For instance, if you like the logs to be red and bold, try this:

```r
library("crayon")
crayon <- function(x) cat(red$bold(x), sep = "\n") 
options("tidylog.display" = list(crayon)) 
```

You could put this in your `.Rprofile` file.
