### ISSUE TITLE
New dplyr join_by breaks with tidylog

### ISSUE THREAD

**Issue by DanSimonet** [elbersb/tidylog#58]
Love the package. Has been immensely helpful for verifying operations are running as expected when walking through long chains. 

I noticed I now receive an error when running the new `join_by` functionality in `dplyr` 1.1.0 while `tidylog` is loaded. Reproducible example:

```
library(tidylog)
library(dplyr)

sales <- tibble(
    id = c(1L, 1L, 1L, 2L, 2L),
    sale_date = as.Date(c("2018-12-31", "2019-01-02", "2019-01-05", "2019-01-04", "2019-01-01"))
)

promos <- tibble(
    id = c(1L, 1L, 2L),
    promo_date = as.Date(c("2019-01-01", "2019-01-05", "2019-01-02"))
)

by <- join_by(id, sale_date == promo_date)
left_join(sales, promos, by)
```

Produces the following error:
```
Error in `dplyr::common_by()`:
! `by` must be a (named) character vector, list, or NULL for natural joins (not recommended in production code), not a <dplyr_join_by> object.
```

**Comment by elbersb** [comment]
Thanks for reporting. Fully supporting this new syntax would be quite a big task, and as I'm no longer using the tidyverse I'm probably not the right person to tackle this. But I did push [a commit](https://github.com/elbersb/tidylog/commit/c68fcb241b2a5a3dbec13dcf1196aef30f41137f) so that there is no longer an error.
